name: Deploy to AWS EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.19"

      - name: Build the Go application
        run: go build -o app main.go

      - name: Deploy to AWS EC2
        run: |
          # Salin file aplikasi ke server EC2
          scp -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY_PATH }} app ${{ secrets.USERNAME }}@${{ secrets.EC2_HOSTNAME }}:/path/to/remote/dir/

          # Jalankan aplikasi di server EC2
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY_PATH }} ${{ secrets.USERNAME }}@${{ secrets.EC2_HOSTNAME }} 'nohup /path/to/remote/dir/app &'
