name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21" # Go version 1.21

      # Build the Go application
      - name: Build the Go application
        run: go build -o app main.go

      # Deploy to EC2
      - name: Deploy application to EC2
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY_PATH }}
          port: 22
          script: |
            echo "Uploading application to EC2"
            scp -i ${{ secrets.SSH_PRIVATE_KEY_PATH }} -o StrictHostKeyChecking=no app ${{ secrets.USERNAME }}@${{ secrets.EC2_HOSTNAME }}:/home/${{ secrets.USERNAME }}
            echo "Starting application on EC2"
            ssh -i ${{ secrets.SSH_PRIVATE_KEY_PATH }} -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.EC2_HOSTNAME }} "chmod +x /home/${{ secrets.USERNAME }}/app && nohup /home/${{ secrets.USERNAME }}/app &"
