name: CI/CD for Go Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20" # Versi Go yang digunakan

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...

      - name: Build application
        run: go build -o ci-cd-go main.go

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.EC2_HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY_PATH }}
          script: |
            # Salin file biner aplikasi ke direktori home pengguna di EC2
            scp ci-cd-go ${USERNAME}@${EC2_HOSTNAME}:~/

            # Jalankan aplikasi di direktori home pengguna
            ssh ${USERNAME}@${EC2_HOSTNAME} "chmod +x ~/ci-cd-go"
            ssh ${USERNAME}@${EC2_HOSTNAME} "~/ci-cd-go &"
